apiVersion: v2
name: cilium-wrapper
description: A wrapper chart for Cilium
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: cilium
    version: 1.16.0
    repository: https://helm.cilium.io/
