- op: replace
  path: /metadata/name
  value: homelab
- op: replace
  path: /spec/clusterNetwork/pods/cidrBlocks
  value:
    - "10.245.0.0/16"
- op: replace
  path: /spec/clusterNetwork/services/cidrBlocks
  value:
    - "10.97.0.0/16"
- op: replace
  path: /spec/infrastructureRef/name
  value: homelab
- op: replace
  path: /spec/controlPlaneRef/name
  value: homelab-cp
