apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: homelab-cp
spec:
  replicas: 1
  infrastructureTemplate:
    name: homelab-cp
  controlPlaneConfig:
    controlplane:
      configPatches:
        - op: replace
          path: /cluster/network/cni
          value:
            name: none
        - op: replace
          path: /cluster/proxy
          value:
            disabled: true
        - op: replace
          path: /machine/install
          value:
            disk: /dev/sda
            image: factory.talos.dev/installer/53513e54bb39202f35694412577a6bc53d484744d35a126e5d42ef34785c0d83:v1.12.6
        - op: add
          path: /machine/kubelet/extraArgs
          value:
            cloud-provider: external
            rotate-server-certificates: "true"
        - op: add
          path: /machine/network
          value:
            interfaces:
              - interface: eth0
                vip:
                  ip: 10.10.0.20
