apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: homelab-cp
spec:
  replicas: 3
  controlPlaneConfig:
    controlplane:
      configPatches:
        - op: replace
          path: /cluster/network/cni
          value:
            name: none
        - op: replace
          path: /cluster/proxy
          value:
            disabled: true
        - op: add
          path: /machine/network
          value:
            interfaces:
              - interface: eth0
                vip:
                  ip: 10.10.0.20
