- op: replace
  path: /metadata/name
  value: homelab-cp
- op: replace
  path: /spec/template/spec/numCores
  value: 4
- op: replace
  path: /spec/template/spec/memoryMiB
  value: 16384
- op: replace
  path: /spec/template/spec/disks/bootVolume/sizeGb
  value: 100
