apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: homelab-workers
spec:
  clusterName: homelab
  replicas: 2
  template:
    spec:
      clusterName: homelab
      bootstrap:
        configRef:
          name: homelab-workers
      infrastructureRef:
        name: homelab-workers
