apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform-management
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            slipway.io/role: management
  template:
    metadata:
      name: 'mgmt-{{name}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/binGhzal/Slipway.git
        targetRevision: main
        path: platform/capi-operator
      destination:
        server: '{{server}}'
        namespace: capi-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
