---
apiVersion: paas.slipway.dev/v1
kind: Plugin
metadata:
  name: ingress-nginx
spec:
  source:
    oci: ghcr.io/kubernetes/ingress-nginx/charts/ingress-nginx:4.11.2
  provides:
    - capability: ingress
      details:
        ingressClass: nginx
---
apiVersion: paas.slipway.dev/v1
kind: Plugin
metadata:
  name: cert-manager
spec:
  source:
    oci: ghcr.io/cert-manager/cert-manager-chart:1.15.3
  values:
    installCRDs: true
  provides:
    - capability: certs
