- op: replace
  path: /metadata/name
  value: slipway-mgmt
- op: replace
  path: /spec/infrastructureRef/name
  value: slipway-mgmt
- op: replace
  path: /spec/controlPlaneRef/name
  value: slipway-mgmt-cp
