apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: slipway-mgmt
  namespace: slipway-mgmt
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - "10.244.0.0/16"
    services:
      cidrBlocks:
        - "10.96.0.0/16"
  infrastructureRef:
    name: slipway-mgmt
  controlPlaneRef:
    name: slipway-mgmt-cp
