apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: slipway-mgmt-cp
spec:
  replicas: 1
  infrastructureTemplate:
    name: slipway-mgmt-cp
  controlPlaneConfig:
    controlplane:
      configPatches:
        - op: replace
          path: /cluster/network/cni
          value:
            name: none
        - op: replace
          path: /cluster/proxy
          value:
            disabled: true
        - op: add
          path: /machine/install/disk
          value: /dev/sda
        - op: add
          path: /machine/kubelet/extraArgs
          value:
            cloud-provider: external
            rotate-server-certificates: "true"
        - op: add
          path: /machine/network
          value:
            interfaces:
              - interface: eth0
                vip:
                  ip: 10.10.0.10
