- op: replace
  path: /metadata/name
  value: slipway-mgmt-cp
- op: replace
  path: /spec/replicas
  value: 1
- op: replace
  path: /spec/infrastructureTemplate/name
  value: slipway-mgmt-cp
# Add VIP to control plane config
- op: add
  path: /spec/controlPlaneConfig/controlplane/strategicPatches/0/machine/network/interfaces/0/vip
  value:
    ip: 10.10.0.10
# Add VIP to init config
- op: add
  path: /spec/controlPlaneConfig/init/strategicPatches/0/machine/network/interfaces/0/vip
  value:
    ip: 10.10.0.10
