apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: slipway-mgmt-cp
spec:
  template:
    spec:
      sourceNode: pve
      templateID: 9000
      numSockets: 2
      numCores: 2
      memoryMiB: 8192
      disks:
        - bootOrder: 1
          bus: scsi
          sizeGb: 50
      network:
        - bridge: vmbr0
          model: virtio
          tag: 2
