- op: replace
  path: /metadata/name
  value: slipway-mgmt
- op: replace
  path: /spec/controlPlaneEndpoint
  value:
    host: "10.10.0.10"
    port: 6443
- op: replace
  path: /spec/ipv4Config/addresses
  value:
    - "10.10.0.11-10.10.0.19"
