gatus:
  config:
    endpoints:
      - name: ArgoCD
        url: "http://argocd-server.argocd.svc.cluster.local"
        interval: 60s
        conditions:
          - "[STATUS] == 200"
      - name: Grafana
        url: "http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local"
        interval: 60s
        conditions:
          - "[STATUS] == 200"
  persistence:
    enabled: true
    size: 1Gi
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
