x509-certificate-exporter:
  secretsExporter:
    resources:
      requests:
        cpu: 20m
        memory: 32Mi
  hostPathsExporter:
    resources:
      requests:
        cpu: 20m
        memory: 32Mi
  prometheusServiceMonitor:
    create: true
  prometheusRules:
    create: true
    alertOnReadErrors: true
    certificateRenewalThreshold: 30
    certificateExpirationThreshold: 14
