apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
kind: TalosControlPlane
metadata:
  name: cluster-name-cp
spec:
  replicas: 1
  version: v1.32.0
  infrastructureTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxMachineTemplate
    name: cluster-name-cp
  controlPlaneConfig:
    controlplane:
      generateType: controlplane
      talosVersion: v1.9
      strategicPatches:
        # Disable default CNI — Cilium will be installed
        - machine:
            install:
              disk: /dev/sda
              extraKernelArgs:
                - net.ifnames=0
            network:
              interfaces:
                - interface: eth0
                  dhcp: true
          cluster:
            network:
              cni:
                name: none
            proxy:
              disabled: true
    init:
      generateType: init
      talosVersion: v1.9
      strategicPatches:
        - machine:
            install:
              disk: /dev/sda
              extraKernelArgs:
                - net.ifnames=0
            network:
              interfaces:
                - interface: eth0
                  dhcp: true
          cluster:
            network:
              cni:
                name: none
            proxy:
              disabled: true
