apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: cluster-name
spec:
  controlPlaneEndpoint:
    host: 0.0.0.0
    port: 6443
  ipv4Config:
    addresses:
      - 10.10.0.11-10.10.0.19
    prefix: 20
    gateway: 10.10.0.1
  dnsServers:
    - 1.1.1.1
    - 8.8.8.8
  allowedNodes:
    - pve
  schedulerHints:
    memoryAdjustment: 0
