apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../bases/proxmox-talos
  - workers.yaml
patches:
  - path: patches/cluster-patch.yaml
  - path: patches/proxmox-cluster-patch.yaml
  - path: patches/control-plane-patch.yaml
  - path: patches/machine-template-patch.yaml
namespace: homelab
