cilium:
  kubeProxyReplacement: true
  ipam:
    mode: kubernetes
  gatewayAPI:
    enabled: true
  hubble:
    relay:
      enabled: true
    ui:
      enabled: true
  l2announcements:
    enabled: true
  externalIPs:
    enabled: true
  encryption:
    enabled: true
    type: wireguard
  bpf:
    masquerade: true
  operator:
    replicas: 1
  bandwidthManager:
    enabled: true
    bbr: true
  hostFirewall:
    enabled: true
  socketLB:
    enabled: true
  localRedirectPolicy: true
  envoy:
    enabled: true
