name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: gofmt -w $(find . -name '*.go')
      - run: go mod tidy
      - run: go build ./...
      - run: go test ./...
